version: '3.1' # Docker version number
services:

  postgres:
    image: postgres:14.19-alpine3.21
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pokemon
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pokemon:
    image: pokemon-web:latest
    ports:
      - 5000:5000
    depends_on:
      - "postgres"

volumes:
  postgres_data:
